### ISSUE TITLE
Typo in the formula - triggered with brew queries (e.g., brew uses formula-name)

### ISSUE THREAD

**Issue by gmerlino** [sdkman/homebrew-tap#5]
Error: Failed to import: /opt/homebrew/Library/Taps/sdkman/homebrew-tap/Formula/sdkmancli.rb
No available formula with the name "sdkmancli". Did you mean sdkman-cli?
In formula file: /opt/homebrew/Library/Taps/sdkman/homebrew-tap/Formula/sdkmancli.rb
**Expected to find class Sdkmancli, but only found: SdkmanCli.**

**Comment by helpermethod** [comment]
Hi @gmerlino!

Did you try to install the formula on Linux?

**Comment by gmerlino** [comment]
on macOS actually

**Comment by helpermethod** [comment]
@gmerlino With the latest changes the problem should be fixed.
